/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.11 --types ./src/assets/3dModels/htmlCssJs.glb --transform -s
*/

import { animated } from "@react-spring/three";
import { useGLTF } from "@react-three/drei";
import * as THREE from "three";
import { GLTF } from "three-stdlib";
import useBounceInAnimation from "../../../../hooks/useBounceInAnimation";
import CanvasHOC from "../CanvasHOC";

type GLTFResult = GLTF & {
  nodes: {
    ["5"]: THREE.Mesh;
    bgBlock5: THREE.Mesh;
  };
};

export const whiteMaterial = new THREE.MeshPhysicalMaterial({
  color: "#fff",
  roughness: 1,
});

const html5Material = new THREE.MeshPhysicalMaterial({
  color: "#ED5133",
  roughness: 1,
  clearcoat: 1,
});

function HtmlModel() {
  const { nodes } = useGLTF(
    "/htmlCssJs-transformed.glb"
  ) as unknown as GLTFResult;

  const { groupRef, springs } = useBounceInAnimation({
    scaleTo: 1,
  });

  return (
    <animated.group dispose={null} ref={groupRef} scale={springs.scale}>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes["5"].geometry}
        material={whiteMaterial}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.bgBlock5.geometry}
        material={html5Material}
      />
    </animated.group>
  );
}

useGLTF.preload("/htmlCssJs-transformed.glb");

export default CanvasHOC(HtmlModel, "HTML");
